name: Install and Configure Velero on EKS with Azure Backup

on:
  workflow_dispatch: 

jobs:
  setup-velero:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Configuring AWS CLI..."
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Set up kubeconfig for EKS
        run: |
          echo "Setting up kubeconfig for EKS..."
          CLUSTER_NAME="my-cluster" # Replace with your EKS cluster name
          aws eks update-kubeconfig --name $CLUSTER_NAME
          
          # Verify Kubernetes access
          kubectl get nodes

      - name: Install Velero CLI
        run: |
          echo "Installing Velero CLI..."
          VELERO_VERSION="v1.15.2"
          DOWNLOAD_URL="https://github.com/vmware-tanzu/velero/releases/download/${VELERO_VERSION}/velero-${VELERO_VERSION}-linux-amd64.tar.gz"
          
          # Download Velero
          curl -L ${DOWNLOAD_URL} -o velero-${VELERO_VERSION}-linux-amd64.tar.gz
          
          # Extract the tar.gz file
          tar -zxvf velero-${VELERO_VERSION}-linux-amd64.tar.gz
          
          # Copy the Velero binary to /usr/local/bin
          sudo cp velero-${VELERO_VERSION}-linux-amd64/velero /usr/local/bin/
          
          # Verify Velero installation
          velero version

      - name: Install Velero on EKS with Azure Backup
        env:
          BLOB_CONTAINER: ${{ secrets.BLOB_CONTAINER }}
          AZURE_BACKUP_RESOURCE_GROUP: ${{ secrets.AZURE_BACKUP_RESOURCE_GROUP }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}
          AZURE_BACKUP_SUBSCRIPTION_ID: ${{ secrets.AZURE_BACKUP_SUBSCRIPTION_ID }}
        run: |
          echo "Creating credentials file for Velero..."
          cat <<EOF > /tmp/credentials-velero
          AZURE_STORAGE_ACCOUNT_ACCESS_KEY=${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
          EOF
          
          echo "Installing Velero on Kubernetes..."
          velero install \
            --provider azure \
            --plugins velero/velero-plugin-for-microsoft-azure:v1.1.0 \
            --bucket $BLOB_CONTAINER \
            --secret-file /tmp/credentials-velero \
            --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_NAME,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
            --use-volume-snapshots=false \
            --use-node-agent
          
          echo "Velero installation complete!"
          sleep 20

      - name: Restore Velero Backup
        env:
          BACKUP_NAME: ${{ secrets.VELERO_BACKUP_NAME }}
        run: |
          velero restore create --from-backup backup-2-12-2025
